query ArticleGQL( $slug: String! ){
    article( slug: $slug ){
        title
        content
        view
        vote
        createTime
        user{
            username
            displayName
        }
    }
}