query ArticleListGQL($page: Int!) {
	articleList(page: $page) {
		maxPage
		ArticleList {
            title
            vote
            view
			user{
				displayName
				username
				gravataremail
			}
			slug
			createTime
		}
	}
}
