query BLogListGQL($page: Int!) {
	blogList(page: $page) {
		maxPage
		blogList {
            title
            vote
            view
			user{
				displayName
				username
				gravataremail
			}
			slug
			createTime
		}
	}
}
