query ProblemDetailGQL($slug: String!) {
	problem(slug: $slug) {
		pk
		title
		content
		standardInput
		standardOutput
		constraints
		resources
		note
		limitation{
			timeLimit
			memoryLimit
			outputLimit
			cpuLimit
		}
		samples {
			sampleList{
				inputContent
				outputContent
			}
		}
	}
}
