mutation RegisterGQL(
	$username: String!
	$password: String!
	$email: String!
	$about: String!
	$school: String
	$company: String
	$location: String
) {
	userRegister(
		username: $username
		password: $password
		email: $email
		about: $about
		school: $school
		company: $company
		location: $location
	) {
		token
		payload
		permission
		user{
			username
			attachInfo{
				gravatar
				school
				company
				location
				about
			}
		}
	}
}
