query UserListGQL($page: Int!, $filter: String) {
	userList(page: $page, filter: $filter) {
		maxPage
		userList {
			username
			attachInfo{
				gravatar
			}
			solved
			tried
			statistics{
				ratio
			}
			rank{
				position
			}
		}
	}
}
