query ProfileGQL($username: String!) {
	user( username: $username){
		username
		attachInfo{
			school
			company
			location
			about
			gravatar
			codeforces
			atcoder
			studentid
			gender
		}
		solved
		tried
		joinedDate
		lastLoginDate
		rank{
			position
			count
		}
		statistics{
			ac
			tle
			ce
			wa
			re
			ole
			mle
			solve{
				pk
				slug
				status
			}
		}
	}
}
