mutation UserInfoUpdateGQL( $about: String! , $company: String! , $school: String!, $location: String!){
        userAttachInfoUpdate( company: $company , about: $about , school: $school, location: $location){
                state
        }
}